version: '2'
services:
    pdanyos-app:
        image: pdanyos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pdanyos-postgresql:5432/pdanyos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pdanyos-postgresql:
        extends:
            file: postgresql.yml
            service: pdanyos-postgresql
