version: '2'
services:
    pdanyos-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/pdanyos/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pdanyos
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
